-- Auto-translated from Postgres -> SQLite for Curio Core.
-- Source: github.com/filecoin-project/curio harmony/harmonydb/sql/20251029-pdp-v0-pieceref-cascade.sql
-- Translation pass: 2026-05-23 (Day 3 scaffolding).
--
-- Bulk substitutions applied:
--   SERIAL/BIGSERIAL PRIMARY KEY -> INTEGER PRIMARY KEY AUTOINCREMENT
--   TIMESTAMP[TZ] -> DATETIME
--   BOOLEAN -> INTEGER, TRUE/FALSE -> 1/0
--   BYTEA -> BLOB
--   JSONB -> TEXT (JSON-serialized at the Go layer)
--   <type>[] -> TEXT (JSON-encoded at the Go layer)
--   UUID -> TEXT, FLOAT -> REAL
--   NOW()/TIMEZONE('UTC',NOW())/CURRENT_TIMESTAMP AT TIME ZONE 'UTC' -> CURRENT_TIMESTAMP
--
-- TODO (manual): the source file contained PG-specific constructs that
-- can't be auto-translated 1:1. Search for `-- TODO: PG-` markers below.
-- Flagged constructs: DO $$ block, DROP CONSTRAINT (limited in SQLite)
--

-- Migration: Rename and update foreign keys on pdp_data_set_piece_adds and pdp_data_set_pieces
-- Changes: Renames old *_pdp_pieceref_fkey constraints and sets them to ON DELETE CASCADE
-- 1. Drop the existing foreign key constraint if it exists
-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--     IF EXISTS (
--         SELECT 1
--         FROM information_schema.table_constraints
--         WHERE constraint_name = 'pdp_proofset_root_adds_pdp_pieceref_fkey'
--           AND table_name = 'pdp_data_set_piece_adds'
--     ) THEN
--         ALTER TABLE pdp_data_set_piece_adds
--             DROP CONSTRAINT pdp_proofset_root_adds_pdp_pieceref_fkey;
--     END IF;
-- END $$;


-- 2. Create the new foreign key constraint with correct name and ON DELETE behavior
-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--     IF NOT EXISTS (
--         SELECT 1
--         FROM pg_constraint
--         WHERE conname = 'pdp_data_set_piece_adds_pdp_pieceref_fkey'
--           AND conrelid = 'pdp_data_set_piece_adds'::regclass
--           AND confdeltype = 'c'
--     ) THEN
--         ALTER TABLE pdp_data_set_piece_adds
--             DROP CONSTRAINT IF EXISTS pdp_data_set_piece_adds_pdp_pieceref_fkey;
--         ALTER TABLE pdp_data_set_piece_adds
--             ADD CONSTRAINT pdp_data_set_piece_adds_pdp_pieceref_fkey
--             FOREIGN KEY (pdp_pieceref)
--             REFERENCES pdp_piecerefs(id)
--             ON DELETE CASCADE;
--     END IF;
-- END
-- $$;



-- ===== MODIFY pdp_data_set_pieces FOREIGN KEY =====

-- 3. Drop the existing foreign key constraint if it exists
-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--     IF EXISTS (
--         SELECT 1
--         FROM information_schema.table_constraints
--         WHERE constraint_name = 'pdp_proofset_roots_pdp_pieceref_fkey'
--           AND table_name = 'pdp_data_set_pieces'
--     ) THEN
--         ALTER TABLE pdp_data_set_pieces
--             DROP CONSTRAINT pdp_proofset_roots_pdp_pieceref_fkey;
--     END IF;
-- END $$;


-- 4. Create the new foreign key constraint with correct name and ON DELETE behavior
-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--     IF NOT EXISTS (
--         SELECT 1
--         FROM pg_constraint
--         WHERE conname = 'pdp_data_set_pieces_pdp_pieceref_fkey'
--           AND conrelid = 'pdp_data_set_pieces'::regclass
--           AND confdeltype = 'c'
--     ) THEN
--         ALTER TABLE pdp_data_set_pieces
--             DROP CONSTRAINT IF EXISTS pdp_data_set_pieces_pdp_pieceref_fkey;
--         ALTER TABLE pdp_data_set_pieces
--             ADD CONSTRAINT pdp_data_set_pieces_pdp_pieceref_fkey
--             FOREIGN KEY (pdp_pieceref)
--             REFERENCES pdp_piecerefs(id)
--             ON DELETE CASCADE;
--     END IF;
-- END
-- $$;

