-- Auto-translated from Postgres -> SQLite for Curio Core.
-- Source: github.com/filecoin-project/curio harmony/harmonydb/sql/20250603-pdp-public-service.sql
-- Translation pass: 2026-05-23 (Day 3 scaffolding).
--
-- Bulk substitutions applied:
--   SERIAL/BIGSERIAL PRIMARY KEY -> INTEGER PRIMARY KEY AUTOINCREMENT
--   TIMESTAMP[TZ] -> DATETIME
--   BOOLEAN -> INTEGER, TRUE/FALSE -> 1/0
--   BYTEA -> BLOB
--   JSONB -> TEXT (JSON-serialized at the Go layer)
--   <type>[] -> TEXT (JSON-encoded at the Go layer)
--   UUID -> TEXT, FLOAT -> REAL
--   NOW()/TIMEZONE('UTC',NOW())/CURRENT_TIMESTAMP AT TIME ZONE 'UTC' -> CURRENT_TIMESTAMP
--
-- TODO (manual): the source file contained PG-specific constructs that
-- can't be auto-translated 1:1. Search for `-- TODO: PG-` markers below.
-- Flagged constructs: DO $$ block
--

-- Create a default "public" PDP service for NullAuth operations
-- This ensures all nodes can add data/proofsets without authentication
-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--     -- Check if "public" service already exists
--     IF NOT EXISTS (SELECT 1 FROM pdp_services WHERE service_label = 'public') THEN
--         -- Create a dummy public key for the public service
--         -- This is a placeholder key that allows NullAuth operations
--         INSERT INTO pdp_services (service_label, pubkey) 
--         VALUES ('public', decode('1C0DE4C0FFEE', 'hex'));
--         
--         -- Log the creation
--         RAISE NOTICE 'Created default "public" PDP service for NullAuth operations';
--     ELSE
--         RAISE NOTICE 'Public PDP service already exists, skipping creation';
--     END IF;
-- END
-- $$;
