-- Auto-translated from Postgres -> SQLite for Curio Core.
-- Source: github.com/filecoin-project/curio harmony/harmonydb/sql/20251004-pdp-v0-indexing.sql
-- Translation pass: 2026-05-23 (Day 3 scaffolding).
--
-- Bulk substitutions applied:
--   SERIAL/BIGSERIAL PRIMARY KEY -> INTEGER PRIMARY KEY AUTOINCREMENT
--   TIMESTAMP[TZ] -> DATETIME
--   BOOLEAN -> INTEGER, TRUE/FALSE -> 1/0
--   BYTEA -> BLOB
--   JSONB -> TEXT (JSON-serialized at the Go layer)
--   <type>[] -> TEXT (JSON-encoded at the Go layer)
--   UUID -> TEXT, FLOAT -> REAL
--   NOW()/TIMEZONE('UTC',NOW())/CURRENT_TIMESTAMP AT TIME ZONE 'UTC' -> CURRENT_TIMESTAMP
--
-- TODO (manual): the source file contained PG-specific constructs that
-- can't be auto-translated 1:1. Search for `-- TODO: PG-` markers below.
-- Flagged constructs: DO $$ block
--

-- fields tracking indexing and ipni jobs over pdp pieces 
-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--     IF NOT EXISTS (
--         SELECT 1
--         FROM information_schema.columns
--         WHERE table_name = 'pdp_piecerefs'
--           AND table_schema = current_schema()
--           AND column_name = 'indexing_task_id'
--     ) THEN
--         ALTER TABLE pdp_piecerefs ADD COLUMN IF NOT EXISTS indexing_task_id BIGINT DEFAULT NULL;
--     END IF;
-- END
-- $$;


-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--     IF NOT EXISTS (
--         SELECT 1
--         FROM information_schema.columns
--         WHERE table_name = 'pdp_piecerefs'
--           AND table_schema = current_schema()
--           AND column_name = 'needs_indexing'
--     ) THEN
--         ALTER TABLE pdp_piecerefs ADD COLUMN IF NOT EXISTS needs_indexing INTEGER DEFAULT FALSE;
--     END IF;
-- END
-- $$;


-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--     IF NOT EXISTS (
--         SELECT 1
--         FROM information_schema.columns
--         WHERE table_name = 'pdp_piecerefs'
--           AND table_schema = current_schema()
--           AND column_name = 'ipni_task_id'
--     ) THEN
--         ALTER TABLE pdp_piecerefs ADD COLUMN IF NOT EXISTS ipni_task_id BIGINT DEFAULT NULL;
--     END IF;
-- END
-- $$;


-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--     IF NOT EXISTS (
--         SELECT 1
--         FROM information_schema.columns
--         WHERE table_name = 'pdp_piecerefs'
--           AND table_schema = current_schema()
--           AND column_name = 'needs_ipni'
--     ) THEN
--         ALTER TABLE pdp_piecerefs ADD COLUMN IF NOT EXISTS needs_ipni INTEGER DEFAULT FALSE;
--     END IF;
-- END
-- $$;

