-- Auto-translated from Postgres -> SQLite for Curio Core.
-- Source: github.com/filecoin-project/curio harmony/harmonydb/sql/20260123-pdp-v0-rename-terminated-at-epoch.sql
-- Translation pass: 2026-05-23 (Day 3 scaffolding).
--
-- Bulk substitutions applied:
--   SERIAL/BIGSERIAL PRIMARY KEY -> INTEGER PRIMARY KEY AUTOINCREMENT
--   TIMESTAMP[TZ] -> DATETIME
--   BOOLEAN -> INTEGER, TRUE/FALSE -> 1/0
--   BYTEA -> BLOB
--   JSONB -> TEXT (JSON-serialized at the Go layer)
--   <type>[] -> TEXT (JSON-encoded at the Go layer)
--   UUID -> TEXT, FLOAT -> REAL
--   NOW()/TIMEZONE('UTC',NOW())/CURRENT_TIMESTAMP AT TIME ZONE 'UTC' -> CURRENT_TIMESTAMP
--
-- TODO (manual): the source file contained PG-specific constructs that
-- can't be auto-translated 1:1. Search for `-- TODO: PG-` markers below.
-- Flagged constructs: DO $$ block, COMMENT ON
--

-- Rename terminated_at_epoch to unrecoverable_proving_failure_epoch
-- This column tracks when a dataset had an unrecoverable proving failure, not necessarily termination

-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--     IF EXISTS (
--         SELECT 1
--         FROM information_schema.columns
--         WHERE table_name = 'pdp_data_sets'
--           AND table_schema = current_schema()
--           AND column_name = 'terminated_at_epoch'
--     ) THEN
--         ALTER TABLE pdp_data_sets RENAME COLUMN terminated_at_epoch TO unrecoverable_proving_failure_epoch;
--     END IF;
-- END
-- $$;


-- (PG COMMENT ON stripped) COMMENT ON COLUMN pdp_data_sets.unrecoverable_proving_failure_epoch IS 'Block height at which an unrecoverable proving failure was detected; NULL if active';
