-- Auto-translated from Postgres -> SQLite for Curio Core.
-- Source: github.com/filecoin-project/curio harmony/harmonydb/sql/20260203-pdp-v0-delete-task-nullable.sql
-- Translation pass: 2026-05-23 (Day 3 scaffolding).
--
-- Bulk substitutions applied:
--   SERIAL/BIGSERIAL PRIMARY KEY -> INTEGER PRIMARY KEY AUTOINCREMENT
--   TIMESTAMP[TZ] -> DATETIME
--   BOOLEAN -> INTEGER, TRUE/FALSE -> 1/0
--   BYTEA -> BLOB
--   JSONB -> TEXT (JSON-serialized at the Go layer)
--   <type>[] -> TEXT (JSON-encoded at the Go layer)
--   UUID -> TEXT, FLOAT -> REAL
--   NOW()/TIMEZONE('UTC',NOW())/CURRENT_TIMESTAMP AT TIME ZONE 'UTC' -> CURRENT_TIMESTAMP
--
-- TODO (manual): the source file contained PG-specific constructs that
-- can't be auto-translated 1:1. Search for `-- TODO: PG-` markers below.
-- Flagged constructs: DO $$ block
--

-- Fix: make delete_data_set_task_id nullable in pdp_delete_data_set
-- The task code sets this column to NULL when the task completes, and queries for IS NULL
-- to find pending work, but the schema incorrectly enforced NOT NULL.
-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--   IF EXISTS (
--     SELECT 1
--     FROM information_schema.columns
--     WHERE table_name = 'pdp_delete_data_set'
--       AND table_schema = current_schema()
--       AND column_name = 'delete_data_set_task_id'
--       AND is_nullable = 'NO'
--   ) THEN
--     ALTER TABLE pdp_delete_data_set
--       ALTER COLUMN delete_data_set_task_id DROP NOT NULL;
--   END IF;
-- END $$;

