-- Auto-translated from Postgres -> SQLite for Curio Core.
-- Source: github.com/filecoin-project/curio harmony/harmonydb/sql/20260414-pdp-v0-fix-add-piece-constraints.sql
-- Translation pass: 2026-05-23 (Day 3 scaffolding).
--
-- Bulk substitutions applied:
--   SERIAL/BIGSERIAL PRIMARY KEY -> INTEGER PRIMARY KEY AUTOINCREMENT
--   TIMESTAMP[TZ] -> DATETIME
--   BOOLEAN -> INTEGER, TRUE/FALSE -> 1/0
--   BYTEA -> BLOB
--   JSONB -> TEXT (JSON-serialized at the Go layer)
--   <type>[] -> TEXT (JSON-encoded at the Go layer)
--   UUID -> TEXT, FLOAT -> REAL
--   NOW()/TIMEZONE('UTC',NOW())/CURRENT_TIMESTAMP AT TIME ZONE 'UTC' -> CURRENT_TIMESTAMP
--
-- TODO (manual): the source file contained PG-specific constructs that
-- can't be auto-translated 1:1. Search for `-- TODO: PG-` markers below.
-- Flagged constructs: DO $$ block, DROP CONSTRAINT (limited in SQLite)
--

-- TODO: PG-DO-block (PostgreSQL procedural). Original kept verbatim.
-- Translation strategy: split the DO block into the imperative SQL
-- statements it would execute; SQLite has no procedural language.
-- DO $$
-- BEGIN
--   IF POSITION('-YB-' IN version()) > 0 THEN
--     IF EXISTS (
--       SELECT 1
--       FROM pg_constraint c
--       WHERE c.conname = 'pdp_data_set_piece_adds_pk'
--         AND c.conrelid = to_regclass('pdp_data_set_piece_adds')
--         AND c.contype = 'p'
--         AND pg_get_indexdef(c.conindid) LIKE
--             '%USING lsm (add_message_hash HASH, add_message_index ASC)%'
--     ) THEN
--       ALTER TABLE pdp_data_set_piece_adds
--         DROP CONSTRAINT pdp_data_set_piece_adds_pk;
-- 
--       EXECUTE 'ALTER TABLE pdp_data_set_piece_adds
--         ADD CONSTRAINT pdp_data_set_piece_adds_pk
--         PRIMARY KEY (add_message_hash, add_message_index)';
--     END IF;
--   END IF;
-- END $$;
